### ISSUE TITLE
com.google.inject.CreationException

### ISSUE THREAD

**Issue by giabao** [giabao/subfolder-evolutions#1]
```
[info] A binding to play.api.db.evolutions.EvolutionsReader was already configured at play.api.db.evolutions.SubFolderEvolutionsModule.bindings(SubFolderEvolutionsModule.scala:10):
[info] Binding(interface play.api.db.evolutions.EvolutionsReader to ConstructionTarget(class play.api.db.evolutions.SubFolderEvolutionsReader)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1).
[info]   at play.api.db.evolutions.EvolutionsModule.bindings(EvolutionsModule.scala:20):
[info] Binding(interface play.api.db.evolutions.EvolutionsReader to ConstructionTarget(class play.api.db.evolutions.EnvironmentEvolutionsReader)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
```

**Comment by giabao** [comment]
This issue is caused by [this line in play's reference.conf](https://github.com/playframework/playframework/blob/2.4.2/framework/src/play/src/main/resources/reference.conf#L132).

When we put `play.modules.disabled += "play.api.db.evolutions.EvolutionsModule"` in `reference.conf` in a .jar library, play Configuration will override with empty `[]` value.

Workaround: Add `play.modules.disabled += "play.api.db.evolutions.EvolutionsModule"` into `application.conf` file in the play application instead.
